### ISSUE TITLE
关于实验结果问题

### ISSUE THREAD

**Issue by OzoneJ** [TreezzZ/SDH_PyTorch#1]
你好，我跑了一下cifar代码，map只有0.108左右，是实验结果和论文中不符么

**Comment by TreezzZ** [comment]
你好，代码已更新，增加了nus-wide, imagenet的实验，现在结果正常了。
参数sigma对实验结果影响很大，之前的代码sigma上传错了，已修正。

**Comment by OzoneJ** [comment]
嗯嗯，学到了，非常感谢～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tree <notifications@github.com&gt;
发送时间: 2019年12月7日 21:15
收件人: TreezzZ/SDH_PyTorch <SDH_PyTorch@noreply.github.com&gt;
抄送: OzoneJ <361199135@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[TreezzZ/SDH_PyTorch] 关于实验结果问题 (#1)
